spring.application.name=App

#para definir el puerto del servidor
server.port=8085

#modificacion de despliegue de h/m logs
logging.pattern.dateformat=hh:mm

spring.main.banner-mode=off

spring.thymeleaf.cache=false

#MySql conexion
spring.datasource.url=jdbc:mysql://localhost:3306/foodplaza?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
 s
#mostrar información en el log
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE